### ISSUE TITLE
Add a `cargo fmt` test to the repo

### ISSUE THREAD

**Issue by mbestavros** [enarx-archive/demo#11]
We'd like to have an automated `rustfmt` test for all incoming pull requests.

An example of such a setup is detailed over on the [Frenetic repo](https://github.com/enarx/frenetic).

**Comment by mbestavros** [comment]
As Nathaniel mentioned in the linked PR: 

> GitHub Actions is pretty useless until everyone has it. This is because tests only run for those in the beta, including those who submit a PR.

We'll revisit when GH Actions is out of beta.

**Comment by npmccallum** [comment]
We can and should still add this using TravisCI.

**Comment by steveej** [comment]
> This is because tests only run for those in the beta, including those who submit a PR.

FWIW, I'm in the beta now ;-)
