### ISSUE TITLE
WASM: Use wasmtime-embed to implement callable Rust functions in Wasmtime

### ISSUE THREAD

**Issue by mbestavros** [enarx-archive/demo#16]
A longer-term WASM priority for Enarx is the ability to implement custom WASI functions in Wasmtime (as detailed in #10). There are a number of approaches to achieve that goal; this issue focuses on one particular way.

Yury from Mozilla has recently been working on tools to make Wasmtime [embeddable](https://github.com/yurydelendik/wasmtime-embed). While they have a number of uses, one particularly interesting result from his work is the ability to write a native Rust function and have it included in the set of functions that Wasmtime imports, and have it usable by WASM binaries. We'd like to investigate this technique as a possibility to achieve custom WASI implementations.

**Comment by steveej** [comment]
The description explains the use-case well now! 

Nitpick: I think the old title would've been fine, as wasmtime-embed is an implementation detail and would fit better into a PR implementing the use-case.
