### ISSUE TITLE
Update the repository description to reflect newly-added demos

### ISSUE THREAD

**Issue by mbestavros** [enarx-archive/demo#27]
Right now, the `demo` repository's description is:

"A demonstration of running encrypted code in an SEV VM"

This was written while the repository only contained the `amd-sev` demo; while appropriate then, we've since reorganized to include a number of demos for various components of the project (Wasmtime, SGX, etc).

Given this description is mirrored in certain places (most notably the [frontpage of the wiki](https://github.com/enarx/enarx.github.io/wiki)), we should change it to something more current and not specific to an individual demo. My suggestion would be:

"A collection of technical demos for components of the Enarx project."

Only the owner can change the repository description, unfortunately. I believe that power currently resides with @npmccallum.

**Comment by steveej** [comment]
I changed it to "A demonstration of various Enarx components", does that warrant closing this issue?

**Comment by mbestavros** [comment]
Yep, I think it does. Thanks!
